// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.se7so.model;

public interface FindPasswordsQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.se7so.model.FindPasswordsQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string query = 1;</code>
   */
  java.lang.String getQuery();
  /**
   * <code>optional string query = 1;</code>
   */
  com.google.protobuf.ByteString
      getQueryBytes();
}
