// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.se7so.model;

public interface PasswordsServiceHealthStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.se7so.model.PasswordsServiceHealthStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>optional string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>optional int32 totalPasswordsLoaded = 2;</code>
   */
  int getTotalPasswordsLoaded();
}
