// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.se7so.model;

public interface UsersQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.se7so.model.UsersQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string users = 1;</code>
   */
  java.lang.String getUsers();
  /**
   * <code>optional string users = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsersBytes();
}
