// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.se7so.model;

public interface UsersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.se7so.model.UsersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.se7so.model.User users = 1;</code>
   */
  java.util.List<com.se7so.model.User> 
      getUsersList();
  /**
   * <code>repeated .com.se7so.model.User users = 1;</code>
   */
  com.se7so.model.User getUsers(int index);
  /**
   * <code>repeated .com.se7so.model.User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .com.se7so.model.User users = 1;</code>
   */
  java.util.List<? extends com.se7so.model.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .com.se7so.model.User users = 1;</code>
   */
  com.se7so.model.UserOrBuilder getUsersOrBuilder(
      int index);
}
