// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package com.se7so.service;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\022\022com.se7so.services\032\033go" +
      "ogle/protobuf/empty.proto\032\013model.proto2r" +
      "\n\020PasswordsService\022^\n\rfindPasswords\022#.co" +
      "m.se7so.model.FindPasswordsQuery\032&.com.s" +
      "e7so.model.FindPasswordsResponse\"\0002\213\001\n\035P" +
      "asswordsServiceHealthService\022j\n\037getPassw" +
      "ordsServiceHealthStatus\022\026.google.protobu" +
      "f.Empty\032-.com.se7so.model.PasswordsServi" +
      "ceHealthStatus\"\000B\036\n\021com.se7so.serviceB\007S" +
      "erviceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.se7so.model.Model.getDescriptor(),
        }, assigner);
    com.google.protobuf.EmptyProto.getDescriptor();
    com.se7so.model.Model.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
