// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package com.se7so.client;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\022\021com.se7so.service\032\013mod" +
      "el.proto\032\036google/protobuf/wrappers.proto" +
      "\032\031google/protobuf/any.proto2Y\n\014UsersServ" +
      "ice\022I\n\010getUsers\022\033.com.se7so.model.UsersQ" +
      "uery\032\036.com.se7so.model.UsersResponse\"\000B\036" +
      "\n\021com.se7so.serviceB\007ServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.se7so.model.Model.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    com.se7so.model.Model.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
